# Site settings
title: Kevin Cunanan Portfolio
email: your-email@domain.com
description: Kevin Cunanan has a ton of good stuff...soon.
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  kcunanan

# Build settings
markdown: kramdown
